version: 0.0
os: linux
files:
  - source: project1.war
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
