version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 300
      runas: root
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
