version: 0.0
os: linux

files:
  - source: project1.war
    destination: /home/ec2-user/app
  - source: scripts/
    destination: /home/ec2-user/app/scripts

hooks:
  BeforeInstall:
    - location: /home/ec2-user/deploy/scripts/beforeInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
