version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "🔨 Maven Build 시작"
      - mvn clean package
  post_build:
    commands:
      - echo "📦 빌드된 WAR 파일을 S3로 복사"
      - aws s3 cp target/project1.war s3://app-deploy-jp/deploy/project1.war

artifacts:
  files:
    - target/project1.war
