version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "[Install 단계] 압축 해제 시작"
      - unzip project1.zip -d Team5
      - cd Team5
      - mvn clean install

  build:
    commands:
      - cd Team5
      - mvn package -DskipTests

  post_build:
    commands:
      - echo "🚀 S3로 WAR 업로드 중..."
      - |
        if [ -f ./Team5/target/jsonExam-0.0.1-SNAPSHOT.war ]; then
          aws s3 cp ./Team5/target/jsonExam-0.0.1-SNAPSHOT.war s3://codepipeline-ap-northeast-1-3a7f194e7885-4948-b1f5-79bc51f17896/
        else
          echo "❌ WAR 파일이 없습니다! 업로드 실패"
          exit 1
        fi

artifacts:
  files:
    - Team5/target/jsonExam-0.0.1-SNAPSHOT.war
  discard-paths: yes
