version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - rm -rf Team5/target
      - unzip -o project1.zip
      - cd Team5
      - mvn clean package -Dmaven.test.skip=true

post_build:
  commands:
    - aws s3 cp Team5/target/*.war s3://app-deploy-jp/

artifacts:
  files:
    - Team5/target/*.war
  discard-paths: yes
