version: 0.2

phases:
  build:
    commands:
      - echo "♥️ 빌드 이미 완료됨. 별도 빌드 안 함."
  post_build:
    commands:
      - echo "📦 배포 파일들 정리 중"
      - mkdir -p deploy
      - cp appspec.yml deploy/
      - cp -r scripts/ deploy/
      - cp project1.war deploy/
artifacts:
  files:
    - deploy/**/*
