version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - rm -rf Team5/target
      - unzip project1.zip -d Team5
      - cd Team5
      - mvn clean package -Dmaven.test.skip=true

artifacts:
  files:
    - Team5/target/*.war
  discard-paths: yes
