version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo ☑️ Install 단계 시작!
      - unzip project1.zip -d Team5        # ← 이름 변경됨
      - export MAVEN_HOME=$CODEBUILD_SRC_DIR/Team5/apache-maven-3.9.5
      - export PATH=$MAVEN_HOME/bin:$PATH
      - cd Team5
      - mvn clean install

  build:
    commands:
      - mvn package -DskipTests

artifacts:
  files:
    - Team5/target/jsonExam-0.0.1-SNAPSHOT.war
  discard-paths: yes
