version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo "[🛠️] Maven 빌드 시작"
      - cd project1
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo "[📦] deploy 디렉토리 구성"
      - mkdir -p ../deploy
      - cp target/project1.war ../deploy/project1.war
      - cd ..
      - cp appspec.yml deploy/
      - cp -r scripts deploy/
      - echo "[✅] deploy 폴더 구성 완료"
      - chmod +x deploy/scripts/*.sh      # ✅ 이 줄 추가
      - ls -alR deploy/

artifacts:
  base-directory: deploy
  files:
    - '**/*'
