name: Upload WAR Package to S3 (Tokyo)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd project1
          mvn clean package -DskipTests

      - name: Prepare deploy package
        run: |
          mkdir deploy
          cp project1/target/project1.war deploy/
          cp appspec.yml deploy/
          cp -r scripts deploy/
          cd deploy
          zip -r deploy-package.zip .

      - name: Upload to S3
        run: |
          aws s3 cp deploy/deploy-package.zip s3://app-deploy-jp/team5-tokyo-build/deploy-package.zip --acl private
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
