
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "🔧 Installing Maven..."
      - yum install -y maven unzip
  build:
    commands:
      - echo "📂 Unzipping project1.zip..."
      - unzip -o project1.zip
      - echo "🔃 Cleaning old build..."
      - rm -rf Team5/target
      - echo "⚙️ Building with Maven..."
      - cd Team5
      - mvn clean package -Dmaven.test.skip=true
  post_build:
    commands:
      - echo "✅ Build completed on `date`"
      - echo "☁️ Uploading WAR file to S3"
      - aws s3 cp Team5/target/*.war s3://app-deploy-jp/

artifacts:
  files:
    - Team5/target/*.war
  discard-paths: yes

